app/blog/models.py
import datetime

from app import db


class Blog(db.Model):
    __tablename__ = "blogs"

    id = db.Column(db.Integer(), primary_key=True)
    # Превью блога (ссылка на изображение)
    preview_url_image = db.Column(db.String(), index=True, nullable=False)
    # Название блога
    title = db.Column(db.String(120), index=True, unique=True, nullable=False)
    # Описание блога
    description = db.Column(db.String(), nullable=False)
    # Кол-во лайков на блоге
    quantity_likes = db.Column(db.Integer(), default=0, index=True, nullable=False)
    # Время создания блога
    created_on = db.Column(db.DateTime(), default=datetime.datetime.utcnow(), nullable=False)
    # Блог скрыт
    is_hide = db.Column(db.Boolean(), default=False, nullable=False)
    # Id пользователя, кому данный блог принадлежит
    user_id = db.Column(db.Integer(), db.ForeignKey("users.id"))
    # Все написанные комментарии под блогом
    comments = db.relationship("Comment", backref="blog")

    def __repr__(self) -> str:
        return f"<Blog {self.title}>"


class Comment(db.Model):
    __tablename__ = "comments"
    id = db.Column(db.Integer(), primary_key=True)
    # Описание комментария
    description = db.Column(db.String(200), nullable=False)
    # Id пользователя, кому данный комментарий принадлежит
    user_id = db.Column(db.Integer(), db.ForeignKey("users.id"))
    # Id блога, под которым написан комментарий
    comment_id = db.Column(db.Integer(), db.ForeignKey("blogs.id"))
    # Время создания комментария
    created_on = db.Column(db.DateTime(), default=datetime.datetime.utcnow(), nullable=False)

    def __repr__(self) -> str:
        return f"<Comment {self.description}>"

app/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, StringField, FileField
from flask_wtf.file import FileAllowed, FileRequired
from app import photos
from wtforms.validators import InputRequired, Length


class BlogForm(FlaskForm):
    title = StringField("title", validators=[InputRequired()])
    photo = FileField(validators=[FileAllowed(photos, "Image only!")])
    description = TextAreaField("description", validators=[InputRequired(), Length(min=0, max=10000)])

app/blog/controllers.py
from typing import Union

from flask import Blueprint, Response, redirect, url_for, render_template, flash, request
from flask_login import login_required
from app import db
from app.blog.controllerblog import CreatorBlog, EditorBlog, DestroyerBlog
from app.blog.forms import BlogForm
from config import AVAILABLE_RESOLUTION_PREVIEW_BLOG

module = Blueprint("blog", __name__)


@module.route("/create_blog/<nickname>", methods=["GET", "POST"])
@login_required
def create_blog(nickname: str) -> Union[str, Response]:
    form = BlogForm()
    if form.validate_on_submit():
        file = request.files["photo"]
        if file.filename == '':
            flash("Изображение не загружено")
            return redirect(url_for("blog.create_blog", nickname=nickname))
        creator_blog: CreatorBlog = CreatorBlog(form.title.data, form.description.data, file)
        if creator_blog.checking_correctness_of_parameters():
            flash("Статья успешно создана")
            creator_blog.add_blog_to_db(nickname)
            return redirect(url_for("profileuser.user", nickname=nickname))
        elif creator_blog.check_existence_similar_block() is True:
            flash("Пост с таким именем уже есть, подумайте над новым названием")
        else:
            resolution = creator_blog.resolution_image
            flash(
                f"Превью загружено в неверном разрешение ({resolution[0]}x{resolution[1]}), "
                f"поддерживаемое разрешение: "
                f"({AVAILABLE_RESOLUTION_PREVIEW_BLOG[0]}x{AVAILABLE_RESOLUTION_PREVIEW_BLOG[1]})")
        return redirect(url_for("blog.create_blog", nickname=nickname))
    return render_template("blog/creating-blog.html", form=form, name_post="Новый блог",
                           name_submit_button="Опубликовать блог", url_image=None)


@module.route("/edit_blog/<nickname>/<title>", methods=["GET", "POST"])
@login_required
def edit_blog(nickname: str, title: str) -> Union[str, Response]:
    form = BlogForm()
    url_image = None
    if form.validate_on_submit():
        file = request.files["photo"]
        if file.filename == '':
            file = None
        editor_blog: EditorBlog = EditorBlog(form.title.data, form.description.data, file)
        if editor_blog.checking_correctness_of_parameters():
            flash("Статья успешно изменена")
            editor_blog.edit_blog_to_bd(title)
            return redirect(url_for("profileuser.user", nickname=nickname))
        else:
            flash("Проблема с выбранным изображением или такой пост уже существует.")
    else:
        blog = EditorBlog.get_blog(title)
        if blog is not None:
            form.title.data = blog.title
            form.description.data = blog.description
            url_image = blog.preview_url_image
        else:
            flash("Упс, данный блог куда-то пропал!")
            return redirect(url_for("profileuser.user", nickname=nickname))
    return render_template("blog/creating-blog.html", form=form, name_post="Редактирование блога",
                           name_submit_button="Сохранить изменения", url_image=url_image)


@module.route("/hide_blog/<nickname>/<title>")
@login_required
def hide_blog(nickname: str, title: str) -> Union[str, Response]:
    blog = CreatorBlog.get_blog(title)
    if blog is not None:
        blog.is_hide = not blog.is_hide
        db.session.add(blog)
        db.session.commit()
    else:
        flash("Упс, данный блог куда-то пропал!")
    return redirect(url_for("profileuser.user", nickname=nickname))


@module.route("/remove_blog/<nickname>/<title>")
@login_required
def remove_blog(nickname: str, title: str) -> Union[str, Response]:
    blog = DestroyerBlog("", "", None)
    blog.remove(title)
    return redirect(url_for("profileuser.user", nickname=nickname))


@module.route("/viewing_blog//<title>")
@login_required
def viewing_blog(title: str) -> Union[str, Response]:
    blog = CreatorBlog.get_blog(title)
    if blog is None:
        flash("Упс, данный блог куда-то пропал!")
        return redirect(url_for("entity.index"))
    return render_template("blog/viewing-blog.html", blog=blog)

app/templates/blog/creating-blog.html
{% extends "base.html" %}

{% block content %}
    <div class="col">
        <h1>{{ name_post }}</h1>
    </div>

    <div class="col">
        <p>Выбранное превью:</p>
        {% if url_image %}
            <div class="col-md-4 px-0">
                <img src="{{ url_image }}" id="img-preview" class="img-fluid">
            </div>
        {% else %}
            <div class="col-md-4 px-0">
                <img id="img-preview" class="img-fluid">
            </div>
        {% endif %}
    </div>
    <div class="col">
        <form action="" method="post" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="row g-3">
                <div class="col-sm-6">
                    <label for="title" class="form-label">Заголовок поста:</label>
                    {{ form.title(maxlength=120, class="form-control") }}
                </div>
                <div class="col-6">
                    <label for="description" class="form-label">Основной текст поста:</label>
                    {{ form.description(rows=25, style="resize: none", class="form-control") }}
                </div>
                <div class="col">
                    <label for="preview" class="form-label">Загрузите превью поста, изображение должно быть следующего
                        разрешния: (1590x400):</label>
                    {{ form.photo(id="img", class="form-control") }}
                </div>
                <hr class="my-4">
                <input class="btn btn-success" type="submit" value="{{ name_submit_button }}">
            </div>
        </form>
    </div>

    <script>
        $('#img').change(function () {
            var input = $(this)[0];
            if (input.files && input.files[0]) {
                if (input.files[0].type.match('image.*')) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $('#img-preview').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(input.files[0]);
                } else {
                    console.log('ошибка, не изображение');
                }
            } else {
                console.log('хьюстон у нас проблема');
            }
        });
    </script>
{% endblock %}

app/templates/blog/preview-blog.html
<div class="card">
    <img class="bd-placeholder-img card-img-top" src="{{ blog.preview_url_image }}">
    <div class="card-body">
        <h5 class="card-title">{{ blog.title }}</h5>
        <p> Пост создан: {{ momentjs(blog.created_on).fromNow() }}</p>
        <div class="row g-3">
            {% if blog.user_id == user.id %}
                <div class="col-2">
                    <a class="btn btn-info"
                       href="{{ url_for('blog.edit_blog', nickname=user.nickname, title=blog.title) }}">Редактировать</a>
                </div>
                <div class="col-12">
                    <a class="btn btn-secondary"
                       href="{{ url_for('blog.hide_blog', nickname=user.nickname, title=blog.title) }}">
                        {% if blog.is_hide %}
                            Показывать статью всем пользователям
                        {% else %}
                            Скрыть статью от остальных пользователей сервиса
                        {% endif %}
                    </a>
                </div>
            {% endif %}
            <div class="col-4">
                <a class="btn btn btn-dark"
                   href="{{ url_for('blog.viewing_blog', title=blog.title) }}">Посмотреть</a>
            </div>
            {% if blog.user_id == user.id %}
                <div class="col-12">
                    <a class="btn btn-danger"
                       href="{{ url_for('blog.remove_blog', nickname=user.nickname, title=blog.title) }}">Удалить</a>
                </div>
            {% endif %}
        </div>
    </div>
</div>

app/templates/blog/viewing-blog.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <img src="{{ blog.preview_url_image }}">
    </div>
    <div class="row">
        <h1 class="featurette-heading">{{ blog.title }}</h1>
    </div>
    <div class="row">
        <p class="lead">{{ blog.description }}</p>
    </div>



{% endblock %}