app/entity/controllers.py
from typing import Union

from flask import Blueprint, g, url_for, request
from flask import render_template, redirect, Response
from flask_login import login_required, login_user, logout_user

from app import db
from app.entity.interactionwithblogs import BlogFilter
from app.profileuser.models import User, ROLE_USER
from .logintoyandex import LoginToYandex
from .userdata import UserData

module = Blueprint("entity", __name__)


@module.route("/get_yandex_token")
def get_yandex_token() -> Union[str, Response]:
    if g.user.is_authenticated:
        return redirect(url_for("entity.index"))

    ly = LoginToYandex()
    if request.args.get('code', False):
        ud: UserData = ly.get_user_data()
        user = User.query.filter(User.email == ud.email).first()
        if user is None:
            nickname = User.make_unique_nickname(ud.first_name)
            user = User(nickname=nickname, email=ud.email, role=ROLE_USER, avatar_id=ud.avatar_id)
            db.session.add(user)
            db.session.commit()
        login_user(user, remember=True)
        return redirect(url_for("entity.index"))
    else:
        access_url = ly.get_access_url()
        return redirect(access_url)


@module.route('/')
@module.route('/index')
@login_required
def index() -> str:
    user = g.user.nickname
    bf = BlogFilter(user)
    blogs = bf.get_other_users_blogs()
    return render_template("main.html", user=user, blogs=blogs)


@module.route("/login")
def login() -> Union[str, Response]:
    if g.user is not None and g.user.is_authenticated:
        return redirect(url_for("index"))
    return render_template("entity/yandex-login.html")


@module.route("/logout")
def logout() -> Response:
    logout_user()
    return redirect(url_for("entity.index"))

app/profileuser/controllers.py
from typing import Union

from flask import Blueprint, Response, flash, redirect, url_for, render_template, g
from flask_login import login_required

from app import db
from app.blog.models import Blog
from app.profileuser.forms import EditForm
from app.profileuser.models import User

module = Blueprint("profileuser", __name__)


@module.route("/user/<nickname>")
@login_required
def user(nickname) -> Union[str, Response]:
    user = User.query.filter(User.nickname == nickname).first()
    if user is None:
        flash(f"Пользователь {nickname} не найден")
        return redirect(url_for("entity.index"))
    blogs = Blog.query.filter(Blog.user_id == user.id).all()
    return render_template("profileuser/user.html", user=user, blogs=blogs)


@module.route("/edit", methods=["GET", "POST"])
@login_required
def edit() -> Union[str, Response]:
    form = EditForm(g.user.nickname)
    if form.validate_on_submit():
        g.user.nickname = form.nickname.data
        g.user.about_me = form.about_me.data
        db.session.add(g.user)
        db.session.commit()
        flash("Изменения были сохранены")
        return redirect(url_for("profileuser.edit"))
    else:
        form.nickname.data = g.user.nickname
        form.about_me.data = g.user.about_me
    return render_template("profileuser/edit.html", form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>MyBlog</title>
    {% endif %}
    <script src="/static/js/moment.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
            integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>


<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">MyBlog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('entity.index') }}">Домой</a>
                    </li>
                    {% if g.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('profileuser.user', nickname = g.user.nickname) }}">Профиль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('blog.create_blog', nickname = g.user.nickname) }}">Написать блог</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('entity.logout') }}">Выйти</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

<main class="container">
    <div class="bg-light p-5 rounded">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li> {{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        {% block content %} {% endblock %}
    </div>
</main>

</body>
</html>

app/templates/comment-base.html
<table>
    <tr valign="top">
        <td><img src="{{ post.author.avatar('islands-middle') }}"></td>
        <td><i>{{ post.author.nickname }} говорит: <br>{{ post.body }}</i></td>
    </tr>
</table>

app/templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1>Hi, {{ user.nickname }}!</h1>
    {% for post in posts %}
        <div>{{ post.author.nickname }} says: <b>{{ post.body }}</b></div>
    {% endfor %}
{% endblock %}

app/templates/main.html
{% extends "base.html" %}
{% block content %}
    <h1>Привет, {{ g.user.nickname }}</h1>
    <div class="row mb-2">
        {% if blogs %}
            {% for blog in blogs %}
                <div class="col-md-6">
                    {% include "blog/preview-blog.html" %}
                </div>
            {% endfor %}
        {% else %}
            <p>Здесь пока ничего нет :(. Но давайте напишем блог для других пользователей, для этого воспользуйтесь
                кнопкой сверху "Написать блог"!.</p>
        {% endif %}
    </div>
{% endblock %}